library(tidyverse)
library(sf)
library(magrittr)
# library(tmap)
# library(tmaptools)
library(terra)
library(extrafont)
library(viridis)
library(MetBrewer)
library(glue)
library(patchwork)
library(units)
library(ggnewscale)
library(ggspatial)
library(shadowtext)
library(png)
library(tidyterra)
library(ggpattern)
library(knitr)
library(fs)
library(units)
library(lwgeom)
library(smoothr)
